language: node_js

node_js:
  - 8.15

services:
  - postgres
  
before_script:
  - yarn run sequelize db:create

jobs:
  include:
    - stage: test
      script: npm test
    - script: yarn run db:migrate

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: n2Z+fXRgMAwsmen4UoUkpQFQ12treZvh9oJfSf3oP+V8JCcHBans8cjtJp1s0tfZRI631mmDpTggriHIxtEClyst4ZpK/DhGJKGfcXi/+fjJjA9lUfBXjkD1XDkYy7KJJU1kPkKWc5pb8RyYuyb+il9FcTpBoGGa/bERYjszszZK43b6c1DGsJu5HCwiVfSEDZlHl64ZCUfQD57D27L+mGSfEeXJEOLQKxO51aGxKX2DbKPDT0IXxLtYPv3HhXOPnbzBTpVdTK8kQS48m5u7MH/Tkzy27fwABdpS2ccE0zmCcVMgIjDyDgTr+N/B6K6prtjKjzELzbA37cFiTkIx4lJq3q63hkl9owMWF1mpW4R0BGn5Q/dJqT8Rjl36uGWU0Dn8GUfH5ap/b6v0Zkw0fUW6lc+jZ+kQJZa4o2Z5n0X/VX2pHI6CL0WPV7NsGlVc6L107JAIcbgUlJTsK2XA8xVTbYYo6/r2YnO98UOfw2VCrT7ddDH4vvRnCSmrlnyD42t/zCBlA3O2WLCcqcaTnISY/pi13fdG8Hv7TPyg1raTIzqOUBsAFc7e224wh3XB+MZE4gUX1QNt8YCq6YTVkFF48C6trDnFuDM5aqgnlu2wDf49ic26N1m3kJ+RCj5ZLa+nhjOryrwiNC4XHo0t8LX/5/v/AKmLjgBMaFFa2fE=
